### ISSUE TITLE
Eval error

### ISSUE THREAD

**Issue by tbearden** [decalage2/ViperMonkey#13]
When running against the sample here (http://pastebin.com/7Pp2p7Yg), I get the below error.  I have tried against several different samples, and always get the same result.

EVALUATED VBA EXPRESSIONS:
Traceback (most recent call last):
  File "./vmonkey.py", line 215, in process_file_scanexpr
    for expression, expr_eval in scan_expressions(all_code):
  File "/home/tbearden/bin/tools/malware/ViperMonkey/vipermonkey/core/__init__.py", line 205, in scan_expressions
    yield (e, e.eval())
TypeError: eval() takes at least 2 arguments (1 given)

Am I missing some requirement?  or just running through weird samples?

**Comment by tbearden** [comment]
Looks like it bombs when it tries to process lines like 'IE8BaR = 176735 + 3265'

**Comment by decalage2** [comment]
scan_expressions was quite old code that I hadn't used for a while. It should be fixed now. Could you please test your code and tell me if it works?

**Comment by tbearden** [comment]
Looks like that fixed it.  Thanks
