### ISSUE TITLE
Explicit License

### ISSUE THREAD

**Issue by Vogel612** [decalage2/ViperMonkey#14]
Hi there. Could you please explicitly include a LICENSE in your root directory? From the last paragraph I assume this is licensed under MIT, but I'm not sure.

FWIW at http://github.com/rubberduck-vba/Rubberduck we're looking into making code analysis inside the VBE to improve the experience. For that we might get some inspiration here.  
It would be helpful if we could be sure that we can use this, otherwise we'll have to reinvent this from scratch.

On that note we have a pretty good VBA Grammar. (Note that it's licensed under GPL). You could build upon it to fix your Parser problems. If you have any code that blows it up, we'd love to hear from you in an issue 😄

**Comment by decalage2** [comment]
Hi @Vogel612, I didn't know about Rubberduck, looks great.

ViperMonkey is published under a BSD license (shown in the readme and all source files), so it is quite permissive. What do you plan to do exactly? I'm just curious, since you already have a quite complete VBA parser, and your project is in C#.

**Comment by Vogel612** [comment]
We're considering implementation of an execution graph for code metrics and escape analysis. The idea is to provide more sophisticated inspections like: "Collection is only updated, but never queried" or "This Sub has a very high cyclomatic complexity". For that we'll need to basically simulate the code. The concepts that we'd have to use are almost completely language agnostic. Then again that's "future versions" for now.

Also we're starting to feel more and more sure that the grammar can deal with whatever valid vba we throw at it. The obfuscated code you deal with might pose a new challenge :) Feel free to drop by
