### ISSUE TITLE
ParserElement not defined

### ISSUE THREAD

**Issue by Viper727** [decalage2/ViperMonkey#30]
Hello ,

I am new to using this tool. 

When I am trying to execute the python code, it shows me this error. 

Traceback (most recent call last):
  File "vmonkey.py", line 103, in <module>
    from core import *
  File "/home/remnux/Desktop/ViperMonkey/ViperMonkey-master/vipermonkey/core/__init__.py", line 91, in <module>
    ParserElement.enablePackrat()
NameError: global name 'ParserElement' is not defined

Any help is highly appreciated.

**Comment by Viper727** [comment]
Not sure if this is related. However, looks like Core module is no longer available.
https://github.com/kennethreitz/showme/issues/5

**Comment by Viper727** [comment]
Thanks.

**Comment by decalage2** [comment]
If you update oletools to v0.52.3 with `pip install -U oletools` it should fix the issue.
