### ISSUE TITLE
ImportError of pyparsing using pypy

### ISSUE THREAD

**Issue by orblatt** [decalage2/ViperMonkey#46]
Traceback (most recent call last):
  File "vmonkey.py", line 88, in <module>
    from pyparsing import *
ImportError: No module named pyparsing

**Comment by decalage2** [comment]
Could you please check if pyparsing is actually installed, using this command?
```
pypy -m pip list
```
If pyparsing is not installed, then you need to run pip install with pypy, i.e.:
```
pypy -m pip install pyparsing
```

**Comment by orblatt** [comment]
You are my savior. I suggest adding unidecode to the requirements.txt file :)
