### ISSUE TITLE
Error when installing vipermonkey with pypy

### ISSUE THREAD

**Issue by opticoax747** [decalage2/ViperMonkey#92]
In an attempt to fix my broken build of vipermonkey, i decided to try installing it with pypy as recommended and have hit another weird roadblock

I installed the requirements.txt ...but now its not working.

  C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\Users\IEUser\Downloads\pypy2.7-v7.2.0-win32\pypy2.7-v7.2.0-win32\include /Tcbuild\temp.win32-2.7\Release\_openssl.c /Fobuild\temp.win32-2.7\Release\build\temp.win32-2.7\Release\_openssl.obj
  _openssl.c
  build\temp.win32-2.7\Release\_openssl.c(498) : fatal error C1083: Cannot open include file: 'openssl/opensslv.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Common Files\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for cryptography

So i decided maybe it doesnt need this that much, so I chugged along and tried to get the other tools installed

welp....The Readme.md is right there....but it doesnt seem to see it just like LibreOffice....these files are all in the requirements.txt so idk why the directions say to download them again????

λ pypy c:\Users\IEUser\Desktop\ViperMonkey-master\ViperMonkey-master\setup.py install
Traceback (most recent call last):
  File "c:\Users\IEUser\Desktop\ViperMonkey-master\ViperMonkey-master\setup.py", line 49, in <module>
    long_description=open("README.md").read(),
IOError: [Errno 2] No such file or directory: 'README.md'

**Comment by opticoax747** [comment]
commented out line 49 and now hit with...

c:\Users\IEUser\Downloads\pypy2.7-v7.2.0-win32\pypy2.7-v7.2.0-win32\site-packages\setuptools\dist.py:331: UserWarning: Normalizing '0.08' to '0.8'
  normalized_version,
running install
running bdist_egg
running egg_info
writing vipermonkey.egg-info\PKG-INFO
writing dependency_links to vipermonkey.egg-info\dependency_links.txt
writing entry points to vipermonkey.egg-info\entry_points.txt
writing requirements to vipermonkey.egg-info\requires.txt
writing top-level names to vipermonkey.egg-info\top_level.txt
warning: manifest_maker: standard file 'setup.py' not found

error: package directory 'vipermonkey' does not exist

**Comment by sry9681** [comment]
I know this is an old issue but I would recommend installing on WSL2 if you are trying to install on a Windows machine, then if you still run into an installation error regarding `Cannot open include file: 'openssl/opensslv.h': No such file or directory` then go ahead and install **libssl-dev** using your linux package manager (_not_ through python pip or pypy pip). Then try installing the requirements.txt file again and it should work.

**Comment by decalage2** [comment]
I'm working on this issue, it's almost solved (see issue #106). To finish fixing it, I need to publish an updated version of oletools to PyPI. Hopefully in the coming days.
