### ISSUE TITLE
Missing utf-8 shebang in vipermonkey/core/vba_library.py

### ISSUE THREAD

**Issue by Te-k** [decalage2/ViperMonkey#95]
**Describe the bug**

Running last ViperMonkey commit with cpython :
```
> vmonkey FILE
SyntaxError: Non-ASCII character '\xc3' in file/ViperMonkey/vipermonkey/core/vba_library.py on line 145, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**To Reproduce**

* Clone the ViperMonkey repo
* do pip install . in the repo
* Launches vmonkey on a file

**Fix**

Just add `#-*- coding: utf-8 -*- ` in vipermonkey/core/vba_library.py

**Comment by decalage2** [comment]
I merged many commits from Kirk Sayre's fork, the UTF-8 characters are now gone. But just in case, I will add the encoding declaration.
